version: '3'
services:
  firefox-syncserver:
    image: mozilla/syncserver:latest
    restart: unless-stopped
    volumes:
      - firefox-syncserver-data:/tmp
     environment:
      - TZ=US/Pacific
      - SYNCSERVER_PUBLIC_URL=https://ffsync.scales.fun
      - SYNCSERVER_SECRET=ADD_SOME_SECRET_HERE
      - SYNCSERVER_SQLURI=sqlite:////tmp/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - SYNCSERVER_ALLOW_NEW_USER=true
      - PORT=5000

volumes:
  firefox-syncserver-data:
