version: '3'
services:
  firefox-syncserver:
    image: mozilla/syncserver:latest
    restart: unless-stopped
    volumes:
      - firefox-syncserver-data:/tmp
      - ${WEBAPP_STORAGE_HOME}/etc/localtime:/etc/localtime:ro
    environment:
      - TZ=US/Pacific
      - SYNCSERVER_PUBLIC_URL=https://ffoxsync.tobyscales.com
      - SYNCSERVER_SECRET=SomeGreatSecret!
      - SYNCSERVER_SQLURI=sqlite:////tmp/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - SYNCSERVER_ALLOW_NEW_USER=true
      - PORT=4500
    labels:
      - traefik.enable=false
      - traefik.frontend.rule=Host:ffoxsync.tobyscales.com
      - traefik.port=4500

volumes:
  firefox-syncserver-data:
