  traefik:
    image: traefik
    command:
      - --logLevel=DEBUG
      - --defaultentrypoints=http,https
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::443 TLS
      - --docker
      - --docker.exposedbydefault=false
      - --docker.domain=scales.fun
      - --acme=true
      - --acme.acmelogging=true
      - --acme.email=webmaster@scales.fun
      - --acme.storage=acme.json
      - --acme.entryPoint=https
      - --acme.onhostrule=true
      - --acme.httpchallenge=true
      - --acme.httpchallenge.entrypoint=http
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/acme.json:/acme.json
    restart: always

