version: '3'
services:
  traefik:
    image: traefik:latest
    command:
      - "--logLevel=INFO"
      - "--defaultentrypoints=http,https"
      - "--entryPoints=Name:http Address::80 Redirect.EntryPoint:https"
      - "--entryPoints=Name:https Address::443 TLS"
      - "--docker"
      - "--docker.exposedbydefault=false"
      - "--docker.domain=scales.fun"
      - "--acme=true"
      - "--acme.acmelogging=true"
      - "--acme.email=encrypt@scales.fun"
      - "--acme.storage=acme.json"
      - "--acme.entryPoint=https"
      - "--acme.onhostrule=true"
      - "--acme.httpchallenge=true"
      - "--acme.httpchallenge.entrypoint=http"
    ports:
      - target: 80
        published: 80
        protocol: tcp
      - target: 443
        published: 443
        protocol: tcp
    volumes:
      - "${WEBAPP_STORAGE_HOME}/acme.json:/acme.json"
      
  firefox-syncserver:
    image: mozilla/syncserver:latest
    restart: unless-stopped
    volumes:
      - firefox-syncserver-data:/tmp
    environment:
      - TZ=US/Pacific
      - SYNCSERVER_PUBLIC_URL=https://ffoxsync.scales.fun
      - SYNCSERVER_SECRET=SomeGreatSecret!
      - SYNCSERVER_SQLURI=sqlite:////tmp/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - SYNCSERVER_ALLOW_NEW_USER=true
      - PORT=5000
    labels:
      - traefik.enable=true
      - "traefik.backend=firefox-syncserver"
      - "traefik.port=5000"
      - "traefik.frontend.rule=Host:ffoxsync.scales.fun"

volumes:
  firefox-syncserver-data:
