version: '3'
services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command: --docker --logLevel="INFO"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ${WEBAPP_STORAGE_HOME}/foxsync/docker.sock:/var/run/docker.sock
      - ${WEBAPP_STORAGE_HOME}/foxsync/traefik.toml:/etc/traefik/traefik.toml
      - ${WEBAPP_STORAGE_HOME}/foxsync/acme.json:/acme.json
      
  firefox-syncserver:
    image: mozilla/syncserver:latest
    restart: unless-stopped
    volumes:
      - firefox-syncserver-data:/tmp
      - ${WEBAPP_STORAGE_HOME}/foxsync/localtime:/etc/localtime:ro
    environment:
      - TZ=US/Pacific
      - SYNCSERVER_PUBLIC_URL=https://ffoxsync.tobyscales.com
      - SYNCSERVER_SECRET=SomeGreatSecret!
      - SYNCSERVER_SQLURI=sqlite:////tmp/syncserver.db
      - SYNCSERVER_BATCH_UPLOAD_ENABLED=true
      - SYNCSERVER_FORCE_WSGI_ENVIRON=true
      - SYNCSERVER_ALLOW_NEW_USER=true
      - PORT=4500
    labels:
      - traefik.enable=false
      - traefik.frontend.rule=Host:ffoxsync.tobyscales.com
      - traefik.port=4500

volumes:
  firefox-syncserver-data:
